'use strict';
const assert=require('assert');const fs=require('fs');const path=require('path');const vm=require('vm');
const G=require('../lib/dashboard/expert_dashboard_gallery');const S=require('../lib/dashboard/dashboard_saved_views');
const root=path.join(__dirname,'..');
const storageSource=fs.readFileSync(path.join(root,'DashboardSavedViewsStorageService.js'),'utf8');
const serviceSource=fs.readFileSync(path.join(root,'ExpertDashboardGalleryService.js'),'utf8');
const html=fs.readFileSync(path.join(root,'ExpertDashboardGalleryWebApp.html'),'utf8');
const router=fs.readFileSync(path.join(root,'CanonicalR2WebAppService.js'),'utf8');
assert(html.includes('data-prh-dash090-gallery="1"'));assert(html.includes('data-financial-payload="false"'));assert(html.includes('data-query-execution="false"'));assert(html.includes('data-financial-write="false"'));assert(html.includes('Создать копию'));assert(html.includes('@media(max-width:620px)'));assert(!/amount_minor|income_minor|expense_minor|cash_flow_minor|balance_minor/i.test(html));
assert(router.includes("gallery: Object.freeze({ file: 'ExpertDashboardGalleryWebApp'"));assert(router.includes("GALLERY_SURFACE: 'gallery'"));
const map=new Map();let writes=0;const props={getProperty:k=>map.has(k)?map.get(k):null,setProperties:u=>{writes++;Object.entries(u).forEach(([k,v])=>map.set(k,String(v)));}};
const lock={held:false,tryLock(){if(this.held)return false;this.held=true;return true;},releaseLock(){this.held=false;}};
const sandbox={PRH_R2_CANONICAL_RUNTIME:{expertDashboardGallery:G,dashboardSavedViews:S},PropertiesService:{getUserProperties:()=>props},LockService:{getUserLock:()=>lock},Utilities:{newBlob:v=>({getBytes:()=>Buffer.from(String(v),'utf8')})},JSON,Number,String,Object,Array,RegExp,Error,Buffer,unescape,encodeURIComponent};
vm.createContext(sandbox);vm.runInContext(storageSource,sandbox);vm.runInContext(serviceSource,sandbox);
const catalog=sandbox.prhDash090PublicCatalog();assert.strictEqual(catalog.presets.length,7);assert.strictEqual(catalog.financial_payload,false);assert(catalog.presets.every(p=>p.status==='AVAILABLE'));
const cloned=sandbox.prhDash090ClonePreset({preset_id:'SPENDING_DRIVERS',view_id:'dash090-spending-drivers-test',name:'Драйверы расходов'});assert.strictEqual(cloned.decision,'APPLIED');assert.strictEqual(cloned.financial_payload,false);assert.strictEqual(writes,1);assert(sandbox.prhDash084StorageReadView_('dash090-spending-drivers-test'));
assert.throws(()=>sandbox.prhDash090ClonePreset({preset_id:'UNKNOWN',view_id:'bad',name:'Bad'}),/DASH090_PRESET_UNKNOWN/);assert.strictEqual(writes,1);
console.log('expert_dashboard_gallery_runtime_contract_test: PASS',{presets:catalog.presets.length,generation:cloned.generation,userPropertiesBatchWrites:writes,financialWrite:false});
