'use strict';

const assert=require('assert');
const CONTRACT=require('../lib/income/income_analytics.v1.json');
const income=require('../lib/income/income_analytics');
const { evaluateKpis }=require('../lib/finance/kpi_dictionary');
const viz=require('../lib/visualization/visualization_foundation');
function expectCode(fn,prefix){let e=null;try{fn();}catch(x){e=x;}assert(e,`Expected ${prefix}`);assert(String(e.code||e.message).startsWith(prefix),`Expected ${prefix}, got ${e.code||e.message}`);}
function tx(id,date,type,amount,category,extra={}){return{transaction_id:id,occurred_at:`${date}T12:00:00Z`,type,status:'posted',amount_minor:amount,currency:extra.currency||'RUB',account_id:extra.account_id||'SYN-ACCOUNT',destination_account_id:type==='transfer'?(extra.destination_account_id||'SYN-SAVINGS'):null,category_id:category||'SYN-OTHER',member_id:extra.member_id||'SYN-MEMBER',project_id:null,tags:['SYNTHETIC'],counterparty:'SYN-COUNTERPARTY',description:'Synthetic income analytics fixture',reverses_transaction_id:extra.reverses_transaction_id||null,adjustment_semantics:extra.adjustment_semantics||null};}
const INPUTS=[
 tx('SYN-25-SAL','2025-01-10','income',40000,'SYN-SALARY'),
 tx('SYN-25-BON','2025-02-10','income',20000,'SYN-BONUS'),
 tx('SYN-25-EXP','2025-02-12','expense',10000,'SYN-FOOD'),
 tx('SYN-26-SAL1','2026-01-10','income',50000,'SYN-SALARY'),
 tx('SYN-26-SAL2','2026-02-10','income',50000,'SYN-SALARY'),
 tx('SYN-26-BON','2026-02-15','income',25000,'SYN-BONUS'),
 tx('SYN-26-EXP','2026-01-12','expense',30000,'SYN-FOOD'),
 tx('SYN-26-TRANSFER','2026-02-20','transfer',20000,'SYN-TRANSFER')
];
const OPTIONS={currency:'RUB',period:{start:'2026-01-01',end:'2026-03-01',partial:false},comparison_period:{start:'2025-01-01',end:'2025-03-01',partial:false},trend_grain:'MONTH',base_filter_context:{schema:viz.FILTER_CONTEXT_SCHEMA,contract_version:viz.VERSION,filters:[{kind:'DIMENSION',field:'account_id',operator:'INCLUDE',values:['SYN-ACCOUNT']}]}};
assert.strictEqual(CONTRACT.schema,'PRH_INCOME_ANALYTICS_V1');assert.strictEqual(CONTRACT.measure,'INCOME');assert.strictEqual(CONTRACT.source_dimension,'category_id');assert.strictEqual(CONTRACT.source_semantics,'CANONICAL_INCOME_CATEGORY_AS_SOURCE');assert.strictEqual(CONTRACT.period.comparison,'EXPLICIT_EQUAL_DAY_WINDOWS_ONLY');assert.strictEqual(CONTRACT.period.implicit_proration,false);assert.strictEqual(CONTRACT.stability.financial_formula_authority,false);assert.strictEqual(CONTRACT.drill.target,'TRANSACTION_EXPLORER');assert.strictEqual(CONTRACT.cost.mode,'FREE_ONLY');assert(Object.values(CONTRACT.authority).every(v=>v===false));
const view=income.buildIncomeAnalytics(INPUTS,OPTIONS);const p=evaluateKpis(INPUTS,{currency:'RUB',period:OPTIONS.period});const c=evaluateKpis(INPUTS,{currency:'RUB',period:OPTIONS.comparison_period});
assert.strictEqual(view.total_income_minor,p.income_minor);assert.strictEqual(view.comparison_income_minor,c.income_minor);assert.strictEqual(view.total_income_minor,125000);assert.strictEqual(view.comparison_income_minor,60000);assert.strictEqual(view.delta_minor,65000);
assert.deepStrictEqual(view.trend.points.map(x=>[x.time_bucket,x.income_minor]),[['2026-01',50000],['2026-02',75000]]);assert.strictEqual(view.trend.sum_minor,125000);for(const point of view.trend.points){assert.strictEqual(point.income_minor,evaluateKpis(INPUTS,{currency:'RUB',period:{start:point.start,end:point.end,partial:false}}).income_minor);}
assert.deepStrictEqual(view.source_mix.rows.map(x=>[x.source_id,x.income_minor]),[['SYN-SALARY',100000],['SYN-BONUS',25000]]);assert.strictEqual(view.source_mix.total_minor,view.total_income_minor);assert.strictEqual(view.source_mix.residual_minor,0);
assert.deepStrictEqual(view.source_deltas.rows.map(x=>[x.source_id,x.delta_minor]),[['SYN-SALARY',60000],['SYN-BONUS',5000]]);assert.strictEqual(view.source_deltas.delta_minor,view.delta_minor);assert.strictEqual(view.source_deltas.rows.reduce((s,x)=>s+x.delta_minor,0),view.delta_minor);
assert.strictEqual(view.stability.state,'READY');assert.strictEqual(view.stability.bucket_count,2);assert.strictEqual(view.stability.mean_minor,62500);assert.strictEqual(view.stability.variance_minor2,156250000);assert.strictEqual(view.stability.stddev_minor,12500);assert.strictEqual(view.stability.coefficient_of_variation,0.2);assert.strictEqual(view.stability.stability_score,80);
assert.deepStrictEqual(view.widgets.map(w=>[w.id,w.chart_spec.type]),[['income-trend','LINE'],['income-source-mix','DONUT'],['income-source-compare','BAR']]);const specs=JSON.stringify(view.widgets);for(const forbidden of ['income_minor','total_income_minor','rows','transactions'])assert(!specs.includes(forbidden));
const line=viz.compileEChartsOption(view.widgets[0].chart_spec,view.render_datasets.trend);const donut=viz.compileEChartsOption(view.widgets[1].chart_spec,view.render_datasets.source_mix);const bar=viz.compileEChartsOption(view.widgets[2].chart_spec,view.render_datasets.source_compare);assert(line.option.series.every(s=>s.type==='line'));assert.strictEqual(donut.option.series[0].type,'pie');assert(bar.option.series.every(s=>s.type==='bar'));
const drill=income.buildIncomeDrill(view,{widget_id:'income-source-mix',source_id:'SYN-SALARY'});assert.strictEqual(drill.schema,income.DRILL_SCHEMA);assert.strictEqual(drill.drill_context.target,'TRANSACTION_EXPLORER');assert.deepStrictEqual(drill.explorer_query.account_ids,['SYN-ACCOUNT']);assert.deepStrictEqual(drill.explorer_query.category_ids,['SYN-SALARY']);assert.strictEqual(drill.explorer_query.date_from,'2026-01-01');assert.strictEqual(drill.explorer_query.date_to,'2026-03-01');const drillText=JSON.stringify(drill);for(const forbidden of ['amount_minor','income_minor','total_income_minor','delta_minor','value_minor'])assert(!drillText.includes(forbidden));
assert(/^[0-9a-f]{64}$/.test(view.telemetry.query_hash));assert(/^[0-9a-f]{64}$/.test(view.telemetry.context_hash));assert.deepStrictEqual(Object.keys(view.telemetry).sort(),['schema','version','query_hash','context_hash','bucket_count','source_count','stability_state','status','reason_code'].sort());const telemetry=JSON.stringify(view.telemetry);for(const forbidden of ['SYN-SALARY','SYN-ACCOUNT','125000','60000','65000'])assert(!telemetry.includes(forbidden));
const zero=income.stabilityFromTrend({points:[{income_minor:0},{income_minor:0}]});assert.strictEqual(zero.state,'NO_INCOME');assert.strictEqual(zero.stability_score,null);assert.strictEqual(zero.coefficient_of_variation,null);
expectCode(()=>income.buildIncomeAnalytics(INPUTS,{...OPTIONS,comparison_period:{start:'2025-01-01',end:'2025-02-28',partial:false}}),'KPI_PERIODS_NOT_COMPARABLE');expectCode(()=>income.buildIncomeAnalytics(INPUTS,{...OPTIONS,period:{start:'2026-01-15',end:'2026-03-15',partial:false},comparison_period:{start:'2025-01-15',end:'2025-03-15',partial:false}}),'INC_TREND_MONTH_ALIGNMENT_REQUIRED');expectCode(()=>income.buildIncomeAnalytics([...INPUTS,tx('SYN-USD','2026-01-07','income',1000,'SYN-SALARY',{currency:'USD'})],OPTIONS),'KPI_MIXED_CURRENCY_UNSUPPORTED');expectCode(()=>income.buildIncomeDrill(view,{widget_id:'missing',source_id:'SYN-SALARY'}),'INC_DRILL_WIDGET_UNKNOWN');
console.log('income_analytics_contract_test: OK',{contract:`${CONTRACT.schema}@${CONTRACT.version}`,finParity:true,trendBuckets:view.trend.points.length,sourceCount:view.source_mix.rows.length,stability:view.stability.stability_score,variance:view.stability.variance_minor2,drillTarget:drill.drill_context.target,configurationOnlySpecs:true,publicTelemetryPayload:false,freeOnly:true,financialWriteAuthority:false});
