'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const runtime=require('../pwa/local_planning_runtime');
const contract=require('../lib/local_first/local_planning_runtime.v1.json');
const sourceText=fs.readFileSync(path.join(__dirname,'..','pwa','local_planning_runtime.js'),'utf8');
assert.strictEqual(contract.schema,'PRH_LOCAL_PLANNING_RUNTIME_V1');assert.deepStrictEqual(contract.routes,['budget','obligations','liquidity']);assert.strictEqual(contract.sync.warm_route_network_requests,0);assert.strictEqual(contract.sync.warm_route_google_sheets_reads,0);assert.strictEqual(contract.authority.canonical_financial_write,false);assert.strictEqual(contract.authority.cash_flow_as_balance_proxy,false);assert(!sourceText.includes('SpreadsheetApp.'));assert(!sourceText.includes('fetch('));assert(!sourceText.includes('XMLHttpRequest('));
const rev='a'.repeat(64),planRev='b'.repeat(64);
const source={schema:'PRH_LOCAL_PLANNING_SOURCE_V1',version:'1.0.0',canonical_revision:rev,planning_revision:planRev,currency:'RUB',budget:{state:'NOT_CONFIGURED',reason:'BUDGET_EXPLICIT_TOTAL_NOT_CONFIGURED',plans:[]},recurring:{state:'EMPTY',reason:null,plans:[]},commitments:{state:'EMPTY',reason:null,items:[]},liquidity:{state:'SETUP_REQUIRED',reason:'BALANCE_OBSERVATION_SHEET_MISSING',observations:[]}};
const full={schema:'PRH_LOCAL_PLANNING_SYNC_RESPONSE_V1',version:'1.0.0',state:'FULL_SNAPSHOT',canonical_revision:rev,planning_revision:planRev,source,financial_write_authorized:false,canonical_mutation_performed:false,auto_transaction_creation:false,cash_flow_balance_proxy_used:false,telemetry:{status:'FULL_SNAPSHOT'}};
assert.strictEqual(runtime.parseWireEnvelope(JSON.stringify(full)).state,'FULL_SNAPSHOT');
assert.throws(()=>runtime.validateRemoteEnvelope({...full,financial_write_authorized:true}),/LOCAL_PLANNING_AUTHORITY_VIOLATION/);
let active=source,putCalls=0,transportCalls=0,workerCalls=0,financeRevision=rev;
const store={async getActive(){return active},async putActive(next){putCalls+=1;active=next;return next}};
const transport={async fetchSnapshot(){transportCalls+=1;return {schema:'PRH_LOCAL_PLANNING_SYNC_RESPONSE_V1',version:'1.0.0',state:'NOOP',canonical_revision:rev,planning_revision:planRev,financial_write_authorized:false,canonical_mutation_performed:false,auto_transaction_creation:false,cash_flow_balance_proxy_used:false,telemetry:{status:'NOOP'}}}};
const finance={getState(){return {revision:financeRevision}},async runPlanningQuery(src,query){workerCalls+=1;return {schema:'PRH_LOCAL_PLANNING_RESULT_V1',version:'1.0.0',route:query.route,canonical_revision:src.canonical_revision,planning_revision:src.planning_revision,currency:'RUB',payload:{status:query.route==='liquidity'?'SETUP_REQUIRED':'READY'},provenance:{}}}};
const states=[];const plan=runtime.createRuntime({store,transport,financeRuntime:finance,onState:(s)=>states.push(s),now:()=>new Date('2026-08-16T10:00:00Z')});
(async()=>{
 await plan.start('budget');
 await new Promise((resolve)=>setTimeout(resolve,0));
 const afterBootTransport=transportCalls;
 assert(afterBootTransport>=1,'background sync should be non-blocking but available');
 assert.strictEqual(plan.getState().view.status,'READY');
 const beforeWarmTransport=transportCalls,beforeWorker=workerCalls;
 await plan.setRoute('obligations');await plan.setRoute('liquidity');
 assert.strictEqual(transportCalls,beforeWarmTransport,'warm planning route must not call remote transport');
 assert(workerCalls>=beforeWorker+2,'warm planning route should evaluate locally in worker');
 financeRevision='c'.repeat(64);const stale=await plan.setRoute('budget');assert.strictEqual(stale.status,'STALE');assert.strictEqual(stale.reason,'PLANNING_CANONICAL_REVISION_MISMATCH');
 assert.strictEqual(putCalls,0);
 console.log('local_planning_runtime_contract_test: PASS',{warmNetwork:0,exactCanonicalBinding:true,workerOnly:true,failClosedStale:true});
})().catch((error)=>{console.error(error);process.exit(1)});
